// <auto-generated />
using HelloWorld.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloWorld.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20240320101407_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("HelloWorld.Entities.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Category 1"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Category 2"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Category 3"
                        });
                });

            modelBuilder.Entity("HelloWorld.Entities.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Description = "Description 1",
                            Name = "Product 1"
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Name = "Product 2"
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 1,
                            Description = "Description 3",
                            Name = "Product 3"
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 2,
                            Description = "Description 4",
                            Name = "Product 4"
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 2,
                            Description = "Description 5",
                            Name = "Product 5"
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 2,
                            Name = "Product 6"
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 3,
                            Description = "Description 7",
                            Name = "Product 7"
                        },
                        new
                        {
                            ID = 8,
                            CategoryID = 3,
                            Name = "Product 8"
                        },
                        new
                        {
                            ID = 9,
                            CategoryID = 3,
                            Description = "Description 9",
                            Name = "Product 9"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
